package com.maville.model;

public enum TypeTravaux {
    TRAVAUX_ROUTIERS,
    TRAVAUX_GAZ_ELECTRICITE,
    CONSTRUCTION_RENOVATION,
    ENTRETIEN_PAYSAGER,
    TRANSPORTS_COMMUN,
    SIGNALISATION_ECLAIRAGE,
    TRAVAUX_SOUTERRAINS,
    TRAVAUX_RESIDENTIELS,
    ENTRETIEN_URBAIN,
    RESEAUX_TELECOMMUNICATION
}
